<?php namespace CsSeoMegaBundlePack\Controllers\AdminPageBuilder\onPageOptimization\Tabs\Meta\includes;
/**
 * Social Analytics Dashboard
 * 
 * @package Backlink Manager
 * @since 1.0.0
 * @author CodeSolz <customer-service@codesolz.net>
 */


class MetaTagAssets {
    
    public static $MTA = array(
        'opt' => array(						// options
                'defaults' => array(
                        'site_org_type' => 'organization',
                        'site_place_id' => 'none',
                        'schema_add_noscript' => 1,
                        'schema_website_json' => 1,
                        'schema_organization_json' => 1,
                        'schema_person_json' => 0,
                        'schema_person_id' => '',
                        'schema_alt_name' => '',
                        'schema_logo_url' => '',
                        'schema_banner_url' => '',
                        'schema_img_max' => 1,
                        'schema_img_width' => 800,			// must be at least 696px for Articles
                        'schema_img_height' => 1600,
                        'schema_img_crop' => 0,
                        'schema_img_crop_x' => 'center',
                        'schema_img_crop_y' => 'center',
                        'schema_desc_len' => 250,			// meta itemprop="description" maximum text length (hard limit)
                        'schema_author_name' => 'display_name',
                        // standard types
                        'schema_type_for_archive_page' => 'webpage.collection',
                        'schema_type_for_attachment' => 'webpage',
                        'schema_type_for_home_index' => 'blog',
                        'schema_type_for_home_page' => 'website',
                        'schema_type_for_page' => 'article',
                        'schema_type_for_post' => 'blog.posting',
                        'schema_type_for_search_page' => 'webpage.search.results',
                        'schema_type_for_user_page' => 'webpage.profile',
                        // custom post types
                        'schema_type_for_article' => 'article',
                        'schema_type_for_book' => 'book',
                        'schema_type_for_blog' => 'blog',
                        'schema_type_for_business' => 'local.business',
                        'schema_type_for_download' => 'product',
                        'schema_type_for_event' => 'event',
                        'schema_type_for_organization' => 'organization',
                        'schema_type_for_other' => 'other',
                        'schema_type_for_person' => 'person',
                        'schema_type_for_place' => 'place',
                        'schema_type_for_product' => 'product',
                        'schema_type_for_recipe' => 'recipe',
                        'schema_type_for_review' => 'review',
                        'schema_type_for_tribe_events' => 'event',
                        'schema_type_for_webpage' => 'webpage',
                        'schema_type_for_website' => 'website',
                        'schema_review_item_type' => 'none',	// Default Reviewed Item Type
                        'seo_desc_len' => 156,			// meta name="description" maximum text length (hard limit)
                        'seo_author_field' => 'gplus',
                        'seo_publisher_url' => '',		// (localized)
                        'fb_publisher_url' => '',		// (localized)
                        'fb_app_id' => '',
                        'fb_admins' => '',
                        'fb_author_name' => 'display_name',
                        'fb_locale' => 'en_US',
                        'og_post_type' => 'article',
                        'og_art_section' => 'none',
                        'og_img_width' => 600,
                        'og_img_height' => 315,
                        'og_img_crop' => 1,
                        'og_img_crop_x' => 'center',
                        'og_img_crop_y' => 'center',
                        'og_img_max' => 1,
                        'og_vid_max' => 1,
                        'og_vid_https' => 1,
                        'og_vid_autoplay' => 1,
                        'og_vid_prev_img' => 0,
                        'og_vid_html_type' => 1,
                        'og_def_img_id_pre' => 'wp',
                        'og_def_img_id' => '',
                        'og_def_img_url' => '',
                        'og_def_img_on_index' => 1,
                        'og_def_img_on_search' => 0,
                        'og_def_vid_url' => '',
                        'og_def_vid_on_index' => 1,
                        'og_def_vid_on_search' => 0,
                        'og_ngg_tags' => 0,
                        'og_page_parent_tags' => 0,
                        'og_page_title_tag' => 0,
                        'og_author_field' => 'facebook',
                        'og_author_fallback' => 0,
                        'og_title_sep' => '-',
                        'og_title_len' => 70,
                        'og_title_warn' => 40,
                        'og_desc_len' => 300,			// maximum length in characters (hard limit)
                        'og_desc_warn' => 200,			// recommended maximum length in characters for Facebook (soft limit)
                        'og_desc_hashtags' => 3,
                        'p_publisher_url' => '',		// (localized)
                        'p_author_name' => 'display_name',	// rich-pin specific article:author
                        'p_dom_verify' => '',
                        'p_add_img_html' => 1,
                        'p_add_nopin_media_img_tag' => 1,
                        'p_add_nopin_header_img_tag' => 1,
                        'tc_site' => '',			// Twitter Business @username (localized)
                        'tc_desc_len' => 200,			// Maximum Description Length (hard limit)
                        'tc_type_post' => 'summary_large_image',
                        'tc_type_default' => 'summary',
                        // summary card
                        'tc_sum_img_width' => 600,		// Summary Card Image Dimensions
                        'tc_sum_img_height' => 600,
                        'tc_sum_img_crop' => 1,
                        'tc_sum_img_crop_x' => 'center',
                        'tc_sum_img_crop_y' => 'center',
                        // large image summary card
                        'tc_lrg_img_width' => 600,		// Large Image Card Img Dimensions
                        'tc_lrg_img_height' => 315,
                        'tc_lrg_img_crop' => 1,
                        'tc_lrg_img_crop_x' => 'center',
                        'tc_lrg_img_crop_y' => 'center',
                        // enable/disable head html tags
                        'add_link_rel_author' => 1,
                        'add_link_rel_canonical' => 0,
                        'add_link_rel_publisher' => 1,
                        'add_link_rel_shortlink' => 0,
                        // facebook
                        'add_meta_property_fb:admins' => 1,
                        'add_meta_property_fb:app_id' => 1,
                        // facebook applink
                        'add_meta_property_al:ios:app_name' => 1,
                        'add_meta_property_al:ios:app_store_id' => 1,
                        'add_meta_property_al:ios:url' => 1,
                        'add_meta_property_al:android:app_name' => 1,
                        'add_meta_property_al:android:package' => 1,
                        'add_meta_property_al:android:url' => 1,
                        'add_meta_property_al:web:url' => 1,
                        'add_meta_property_al:web:should_fallback' => 1,
                        // open graph
                        'add_meta_property_og:altitude' => 1,
                        'add_meta_property_og:description' => 1,
                        'add_meta_property_og:image:secure_url' => 1,
                        'add_meta_property_og:image' => 1,
                        'add_meta_property_og:image:width' => 1,
                        'add_meta_property_og:image:height' => 1,
                        'add_meta_property_og:latitude' => 1,
                        'add_meta_property_og:locale' => 1,
                        'add_meta_property_og:longitude' => 1,
                        'add_meta_property_og:site_name' => 1,
                        'add_meta_property_og:title' => 1,
                        'add_meta_property_og:type' => 1,
                        'add_meta_property_og:updated_time' => 1,
                        'add_meta_property_og:url' => 1,
                        'add_meta_property_og:video:secure_url' => 1,
                        'add_meta_property_og:video:url' => 1,
                        'add_meta_property_og:video:type' => 1,
                        'add_meta_property_og:video:width' => 1,
                        'add_meta_property_og:video:height' => 1,
                        'add_meta_property_og:video:tag' => 0,
                        // open graph (article)
                        'add_meta_property_article:author' => 1,
                        'add_meta_property_article:publisher' => 1,
                        'add_meta_property_article:published_time' => 1,
                        'add_meta_property_article:modified_time' => 1,
                        'add_meta_property_article:expiration_time' => 1,
                        'add_meta_property_article:section' => 1,
                        'add_meta_property_article:tag' => 1,
                        // open graph (book)
                        'add_meta_property_book:author' => 1,
                        'add_meta_property_book:isbn' => 1,
                        'add_meta_property_book:release_date' => 1,
                        'add_meta_property_book:tag' => 1,
                        // open graph (music)
                        'add_meta_property_music:album' => 1,
                        'add_meta_property_music:album:disc' => 1,
                        'add_meta_property_music:album:track' => 1,
                        'add_meta_property_music:creator' => 1,
                        'add_meta_property_music:duration' => 1,
                        'add_meta_property_music:musician' => 1,
                        'add_meta_property_music:release_date' => 1,
                        'add_meta_property_music:song' => 1,
                        'add_meta_property_music:song:disc' => 1,
                        'add_meta_property_music:song:track' => 1,
                        // open graph (place)
                        'add_meta_property_place:location:altitude' => 1,
                        'add_meta_property_place:location:latitude' => 1,
                        'add_meta_property_place:location:longitude' => 1,
                        'add_meta_property_place:street_address' => 1,
                        'add_meta_property_place:locality' => 1,
                        'add_meta_property_place:region' => 1,
                        'add_meta_property_place:postal_code' => 1,
                        'add_meta_property_place:country_name' => 1,
                        // open graph (product)
                        'add_meta_property_product:availability' => 1,
                        'add_meta_property_product:condition' => 1,
                        'add_meta_property_product:price:amount' => 1,
                        'add_meta_property_product:price:currency' => 1,
                        'add_meta_property_product:weight:value' => 1,
                        'add_meta_property_product:weight:units' => 1,
                        // open graph (profile)
                        'add_meta_property_profile:first_name' => 1,
                        'add_meta_property_profile:last_name' => 1,
                        'add_meta_property_profile:username' => 1,
                        'add_meta_property_profile:gender' => 1,
                        // open graph (video)
                        'add_meta_property_video:actor' => 1,
                        'add_meta_property_video:actor:role' => 1,
                        'add_meta_property_video:director' => 1,
                        'add_meta_property_video:writer' => 1,
                        'add_meta_property_video:duration' => 1,
                        'add_meta_property_video:release_date' => 1,
                        'add_meta_property_video:tag' => 1,
                        'add_meta_property_video:series' => 1,
                        // seo
                        'add_meta_name_author' => 1,
                        'add_meta_name_description' => 1,
                        'add_meta_name_generator' => 1,
                        // pinterest
                        'add_meta_name_p:domain_verify' => 1,
                        // weibo
                        'add_meta_name_weibo:article:create_at' => 1,
                        'add_meta_name_weibo:article:update_at' => 1,
                        // twitter cards
                        'add_meta_name_twitter:card' => 1,
                        'add_meta_name_twitter:creator' => 1,
                        'add_meta_name_twitter:domain' => 1,
                        'add_meta_name_twitter:site' => 1,
                        'add_meta_name_twitter:title' => 1,
                        'add_meta_name_twitter:description' => 1,
                        'add_meta_name_twitter:image' => 1,
                        'add_meta_name_twitter:image:width' => 1,
                        'add_meta_name_twitter:image:height' => 1,
                        'add_meta_name_twitter:player' => 1,
                        'add_meta_name_twitter:player:stream' => 1,
                        'add_meta_name_twitter:player:stream:content_type' => 1,
                        'add_meta_name_twitter:player:width' => 1,
                        'add_meta_name_twitter:player:height' => 1,
                        'add_meta_name_twitter:app:name:iphone' => 1,
                        'add_meta_name_twitter:app:id:iphone' => 1,
                        'add_meta_name_twitter:app:url:iphone' => 1,
                        'add_meta_name_twitter:app:name:ipad' => 1,
                        'add_meta_name_twitter:app:id:ipad' => 1,
                        'add_meta_name_twitter:app:url:ipad' => 1,
                        'add_meta_name_twitter:app:name:googleplay' => 1,
                        'add_meta_name_twitter:app:id:googleplay' => 1,
                        'add_meta_name_twitter:app:url:googleplay' => 1,
                        // schema link
                        'add_link_itemprop_url' => 1,
                        'add_link_itemprop_image' => 1,
                        'add_link_itemprop_image.url' => 1,
                        'add_link_itemprop_author.url' => 1,
                        'add_link_itemprop_author.image' => 1,
                        'add_link_itemprop_contributor.url' => 1,
                        'add_link_itemprop_contributor.image' => 1,
                        'add_link_itemprop_menu' => 1,
                        // schema meta
                        'add_meta_itemprop_name' => 1,
                        'add_meta_itemprop_alternatename' => 1,
                        'add_meta_itemprop_description' => 1,
                        'add_meta_itemprop_email' => 1,
                        'add_meta_itemprop_telephone' => 1,
                        'add_meta_itemprop_address' => 1,
                        'add_meta_itemprop_datepublished' => 1,
                        'add_meta_itemprop_datemodified' => 1,
                        'add_meta_itemprop_image.width' => 1,
                        'add_meta_itemprop_image.height' => 1,
                        'add_meta_itemprop_publisher.name' => 1,
                        'add_meta_itemprop_author.name' => 1,
                        'add_meta_itemprop_author.description' => 1,
                        'add_meta_itemprop_contributor.name' => 1,
                        'add_meta_itemprop_contributor.description' => 1,
                        'add_meta_itemprop_openinghoursspecification.dayofweek' => 1,
                        'add_meta_itemprop_openinghoursspecification.opens' => 1,
                        'add_meta_itemprop_openinghoursspecification.closes' => 1,
                        'add_meta_itemprop_openinghoursspecification.validfrom' => 1,
                        'add_meta_itemprop_openinghoursspecification.validthrough' => 1,
                        'add_meta_itemprop_currenciesaccepted' => 1,
                        'add_meta_itemprop_paymentaccepted' => 1,
                        'add_meta_itemprop_pricerange' => 1,
                        'add_meta_itemprop_acceptsreservations' => 1,
                        'add_meta_itemprop_aggregaterating.ratingvalue' => 1,
                        'add_meta_itemprop_aggregaterating.ratingcount' => 1,
                        'add_meta_itemprop_aggregaterating.worstrating' => 1,
                        'add_meta_itemprop_aggregaterating.bestrating' => 1,
                        'add_meta_itemprop_aggregaterating.reviewcount' => 1,
                        'add_meta_itemprop_startdate' => 1,		// Schema Event
                        'add_meta_itemprop_enddate' => 1,		// Schema Event
                        'add_meta_itemprop_location' => 1,		// Schema Event
                        'add_meta_itemprop_preptime' => 1,		// Schema Recipe
                        'add_meta_itemprop_cooktime' => 1,		// Schema Recipe
                        'add_meta_itemprop_totaltime' => 1,		// Schema Recipe
                        'add_meta_itemprop_recipeyield' => 1,		// Schema Recipe
                        'add_meta_itemprop_recipeingredient' => 1,	// Schema Recipe (supersedes ingredients)
                        'add_meta_itemprop_recipeinstructions' => 1,	// Schema Recipe
                    
                    // Contact Field Names and Labels
                        'plugin_cm_fb_name' => 'facebook',
                        'plugin_cm_fb_label' => 'Facebook User URL',
                        'plugin_cm_fb_enabled' => 1,
                        'plugin_cm_gp_name' => 'gplus',
                        'plugin_cm_gp_label' => 'Google+ URL',
                        'plugin_cm_gp_enabled' => 1,
                        'plugin_cm_instgram_name' => 'instagram',
                        'plugin_cm_instgram_label' => 'Instagram URL',
                        'plugin_cm_instgram_enabled' => 1,
                        'plugin_cm_linkedin_name' => 'linkedin',
                        'plugin_cm_linkedin_label' => 'LinkedIn URL',
                        'plugin_cm_linkedin_enabled' => 1,
                        'plugin_cm_myspace_name' => 'myspace',
                        'plugin_cm_myspace_label' => 'Myspace URL',
                        'plugin_cm_myspace_enabled' => 1,
                        'plugin_cm_pin_name' => 'pinterest',
                        'plugin_cm_pin_label' => 'Pinterest URL',
                        'plugin_cm_pin_enabled' => 1,
                        'plugin_cm_sc_name' => 'soundcloud',
                        'plugin_cm_sc_label' => 'Soundcloud URL',
                        'plugin_cm_sc_enabled' => 1,
                        'plugin_cm_tumblr_name' => 'tumblr',
                        'plugin_cm_tumblr_label' => 'Tumblr URL',
                        'plugin_cm_tumblr_enabled' => 1,
                        'plugin_cm_twitter_name' => 'twitter',
                        'plugin_cm_twitter_label' => 'Twitter @username',
                        'plugin_cm_twitter_enabled' => 1,
                        'plugin_cm_yt_name' => 'youtube',
                        'plugin_cm_yt_label' => 'YouTube Channel URL',
                        'plugin_cm_yt_enabled' => 1,
                        'plugin_cm_skype_name' => 'skype',
                        'plugin_cm_skype_label' => 'Skype Username',
                        'plugin_cm_skype_enabled' => 1,
                        'wp_cm_aim_name' => 'aim',
                        'wp_cm_aim_label' => 'AIM',
                        'wp_cm_aim_enabled' => 1,
                        'wp_cm_jabber_name' => 'jabber',
                        'wp_cm_jabber_label' => 'Google Talk',
                        'wp_cm_jabber_enabled' => 1,
                        'wp_cm_yim_name' => 'yim',
                        'wp_cm_yim_label' => 'Yahoo Messenger',
                        'wp_cm_yim_enabled' => 1,
                        /*
                         * Advanced Settings
                         */
                ),	// end of defaults
                'cf_md_idx' => array(		// custom field to meta data index
                        'plugin_cm_img_url' => 'og_img_url',
                        'plugin_cm_vid_url' => 'og_vid_url',
                        'plugin_cm_vid_embed' => 'og_vid_embed',
                        'plugin_cm_recipe_ingredients' => 'schema_recipe_ingredient',
                        'plugin_cm_recipe_instructions' => 'schema_recipe_instruction',
                        'plugin_cm_product_avail' => 'product_avail',
                        'plugin_cm_product_condition' => 'product_condition',
                        'plugin_cm_product_price' => 'product_price',
                        'plugin_cm_product_currency' => 'product_currency',
                ),
            'cm_prefix' => array(		// contact method options prefix
                        'email' => 'email',
                        'facebook' => 'fb',
                        'gplus' => 'gp',
                        'twitter' => 'twitter',
                        'instagram' => 'instgram',
                        'linkedin' => 'linkedin',
                        'myspace' => 'myspace',
                        'pinterest' => 'pin',
                        'pocket' => 'pocket',
                        'buffer' => 'buffer',
                        'reddit' => 'reddit',
                        'managewp' => 'managewp',
                        'stumbleupon' => 'stumble',
                        'tumblr' => 'tumblr',
                        'youtube' => 'yt',
                        'skype' => 'skype',
                        'vk' => 'vk',
                        'whatsapp' => 'wa',
                ),
                'md_multi' => array(		// read values into numeric meta data index
                        'schema_recipe_ingredient' => true,
                        'schema_recipe_instruction' => true,
                ),
        ),
        'twitter_meta' => array(
            'summary' => array( 'twitter:card', 'twitter:domain', 'twitter:site', 'twitter:title', 'twitter:description', 'twitter:image' ),
            'summary_large_image' => array( 'twitter:card', 'twitter:domain', 'twitter:site', 'twitter:creator', 'twitter:title', 'twitter:description', 'twitter:image'),
            'app' => array( 'twitter:card', 'twitter:domain', 'twitter:site', 'twitter:description', 'twitter:app:country', 'twitter:app:name:iphone', 'twitter:app:id:iphone', 'twitter:app:url:iphone', 'twitter:app:name:ipad', 'twitter:app:id:ipad', 'twitter:app:url:ipad', 'twitter:app:name:googleplay', 'twitter:app:id:googleplay', 'twitter:app:url:googleplay'),
            'player' => array( 'twitter:card', 'twitter:domain', 'twitter:title', 'twitter:site', 'twitter:description', 'twitter:player', 'twitter:player:width', 'twitter:player:height', 'twitter:image', 'twitter:image:alt', 'twitter:player:stream', 'twitter:player:stream:content_type')
        ),
        'og_image_attr' => array(
            'summary' => array( 'tc_sum_img_width', 'tc_sum_img_height', 'tc_sum_img_crop' ),
            'summary_large_image' => array( 'tc_lrg_img_width', 'tc_lrg_img_height', 'tc_lrg_img_crop' ),
            'og_img' => array( 'og_img_width', 'og_img_height', 'og_img_crop' ),
            'schema_img' => array( 'schema_img_width', 'schema_img_height', 'schema_img_crop' )
        ),
        'common_og_tags' => array(
            'og:url', 'og:type', 'og:locale', 'og:site_name', 'og:title', 'og:description'
        ),
        'og_image_properties' => array(
            'og:image:secure_url' => '', 'og:image:type' => '', 'og:image:width' => '', 'og:image:height' => '', 'og:image:alt' => ''
        ),
        'webmaster_tags' => array(
            'google' => 'google-site-verification', 'bing' => 'msvalidate.01', 'pinterest' => 'p:domain_verify', 'yandex' => 'yandex-verification'
        ),
        'um' => array(				// update manager
                'min_version' => '1.6.2',	// minimum update manager version (hard limit)
                'check_hours' => array(
                        24 => 'Every day',
                        48 => 'Every two days',
                        72 => 'Every three days',
                        96 => 'Every four days',
                        120 => 'Every five days',
                        144 => 'Every six days',
                        168 => 'Every week',
                        336 => 'Every two weeks',
                        504 => 'Every three weeks',
                        720 => 'Every month',
                ),
                'version_filter' => array(
                        'dev' => 'Development and Up',
                        'alpha' => 'Alpha and Up',
                        'beta' => 'Beta and Up',
                        'rc' => 'Release Candidate and Up',
                        'stable' => 'Stable / Production',
                ),
                'version_regex' => array(
                        'dev' => '/^[0-9][0-9\.\-]+(dev|a|alpha|b|beta|rc)?[0-9\.\+]+$/',
                        'alpha' => '/^[0-9][0-9\.\-]+(a|alpha|b|beta|rc)?[0-9\.\+]+$/',
                        'beta' => '/^[0-9][0-9\.\-]+(b|beta|rc)?[0-9\.\+]+$/',
                        'rc' => '/^[0-9][0-9\.\-]+(rc)?[0-9\.\+]+$/',
                        'stable' => '/^[0-9][0-9\.\+\-]+$/',
                ),
        ),
        'wp' => array(				// wordpress
                'label' => 'WordPress',
                /*
                 * https://codex.wordpress.org/Supported_Versions
                 *
                 * The only current officially supported version is WordPress 4.7.1. Previous major
                 * releases from 3.7 onwards may or may not get security updates as serious exploits
                 * are discovered.
                 */
                'min_version' => '3.7',		// hard limit - deactivate the plugin when activating
                'rec_version' => '4.7',		// soft limit - issue warning if lower version found
                'version_url' => 'https://codex.wordpress.org/Supported_Versions?nocache=1',
        ),
        'php' => array(				// php
                'label' => 'PHP',
                'min_version' => '5.3',		// hard limit - deactivate the plugin when activating
                'rec_version' => '5.6',		// soft limit - issue warning if lower version found
                'version_url' => 'http://php.net/supported-versions.php',
                'extensions' => array(
                    'curl' => 'Client URL Library (cURL)',
                    'json' => 'JavaScript Object Notation (JSON)',
                    'mbstring' => 'Multibyte String',
                    'simplexml' => 'SimpleXML',
                ),
        ),
        'form' => array(
				'max_hashtags' => 5,
				'max_media_items' => 10,
				'weekdays' => array(
					'sunday'         => 'Sunday',
					'monday'         => 'Monday',
					'tuesday'        => 'Tuesday',
					'wednesday'      => 'Wednesday',
					'thursday'       => 'Thursday',
					'friday'         => 'Friday',
					'saturday'       => 'Saturday',
					'publicholidays' => 'Public Holidays',
				),
				'time_seconds' => array(	// in seconds
					'hour'  => HOUR_IN_SECONDS,
					'day'   => DAY_IN_SECONDS,
					'week'  => WEEK_IN_SECONDS,	// 7 days
					'month' => MONTH_IN_SECONDS,	// 30 days
					'year'  => YEAR_IN_SECONDS,	// 365 days
				),
				'time_text' => array(
					'hour'  => 'Hour',
					'day'   => 'Day',
					'week'  => 'Week',
					'month' => 'Month',
					'year'  => 'Year',
				),
				'qualifiers' => array(
					'default'    => '(default)',
					'no_images'  => '(no images)',
					'no_videos'  => '(no videos)',
					'settings'   => '(settings value)',
					'disabled'   => '(option disabled)',
					'default_is' => 'default is %s',
					'checked'    => 'checked',
					'unchecked'  => 'unchecked',
					'at'         => 'at',
					'tz'         => 'tz',
				),
				'user_name_fields' => array(
					'none'         => '[None]',
					'fullname'     => 'First and Last Names',
					'display_name' => 'Display Name',
					'nickname'     => 'Nickname',
				),
				'org_select' => array(
					'none' => '[None]',
					'new'  => '[New Organization]',
					'site' => '[WebSite Organization]',
				),
				'addr_select' => array(
					'none'   => '[None]',
					'custom' => '[Custom Address]',
					'new'    => '[New Address]',
				),
				'show_options' => array(
					'basic' => 'Basic Options',
					'all'   => 'All Options',
				),
				'site_option_use' => array(
					'default' => 'New activation',
					'empty'   => 'If value is empty',
					'force'   => 'Force this value',
				),
				'position_crop_x' => array(
					'left'   => 'Left',
					'center' => 'Center',
					'right'  => 'Right',
				),
				'position_crop_y' => array(
					'top' => 'Top',
					'center' => 'Center',
					'bottom' => 'Bottom',
				),
				'breadcrumbs_for_posts' => array(
					'none'       => '[None]',
					'categories' => 'Categories',
					'ancestors'  => 'Parents',
				),
				'breadcrumbs_for_terms' => array(
					'none'      => '[None]',
					'ancestors' => 'Parents',
				),
				// shortener key is also its filename under lib/pro/ext/
				'shorteners' => array(
					'none'    => '[None]',
					'bitly'   => 'Bitly (suggested)',
					'googl'   => 'Google',
					'owly'    => 'Ow.ly',
					'tinyurl' => 'TinyURL',
					'yourls'  => 'YOURLS',
				),
				// social account keys and labels for organization sameas
				'social_accounts' => array(
					'fb_publisher_url'       => 'Facebook Business Page URL',
					'instgram_publisher_url' => 'Instagram Business Page URL',
					'linkedin_publisher_url' => 'LinkedIn Company Page URL',
					'myspace_publisher_url'  => 'Myspace Business Page URL',
					'p_publisher_url'        => 'Pinterest Company Page URL',
					'sc_publisher_url'       => 'Soundcloud Business Page URL',
					'seo_publisher_url'      => 'Google+ Business Page URL',
					'tc_site'                => 'Twitter Business @username',
					'tumblr_publisher_url'   => 'Tumblr Business Page URL',
					'yt_publisher_url'       => 'YouTube Business Channel URL',
				),
				'embed_media_apis' => array(
					'plugin_facebook_api'   => 'Facebook Videos',
					'plugin_slideshare_api' => 'Slideshare Presentations',
					'plugin_soundcloud_api' => 'Soundcloud Tracks',
					'plugin_vimeo_api'      => 'Vimeo Videos',
					'plugin_wistia_api'     => 'Wistia Videos',
					'plugin_wpvideo_api'    => 'WordPress Video Shortcode',
					'plugin_youtube_api'    => 'YouTube Videos and Playlists',
				),
				// https://schema.org/ItemAvailability
				// {schema_property_value} => {select_value_shown}
				'item_availability' => array(
					'none'                => '[None]',
			 		'Discontinued'        => 'Discontinued',
			 		'InStock'             => 'In Stock',
			 		'InStoreOnly'         => 'In Store Only',
			 		'LimitedAvailability' => 'Limited Availability',
			 		'OnlineOnly'          => 'Online Only',
			 		'OutOfStock'          => 'Out of Stock',
			 		'PreOrder'            => 'Pre-Order',
			 		'SoldOut '            => 'Sold Out',
				),
				// https://schema.org/OfferItemCondition
				// {schema_property_value} => {select_value_shown}
				'item_condition' => array(
					'none'                 => '[None]',
					'DamagedCondition'     => 'Damaged',
					'NewCondition'         => 'New',
					'RefurbishedCondition' => 'Refurbished',
					'UsedCondition'        => 'Used',
				),
				// https://developers.google.com/search/docs/data-types/job-postings
				// {schema_property_value} => {select_value_shown}
				'employment_type' => array(
					'full_time'  => 'Full Time',
					'part_time'  => 'Part Time',
					'contractor' => 'Contractor',
					'temporary'  => 'Temporary',
					'intern'     => 'Intern',
					'volunteer'  => 'Volunteer',
					'per_diem'   => 'Per Diem',
					'other'      => 'Other',
				),
				'cf_labels' => array(		// custom field option labels
                                    'plugin_cm_img_url'             => 'Image URL Custom Field',
                                    'plugin_cm_vid_url'             => 'Video URL Custom Field',
                                    'plugin_cm_vid_embed'           => 'Video Embed HTML Custom Field',
                                    'plugin_cm_addl_type_urls'      => 'Additional Type URLs Custom Field',
                                    'plugin_cm_recipe_ingredients'  => 'Recipe Ingredients Custom Field',
                                    'plugin_cm_recipe_instructions' => 'Recipe Instructions Custom Field',
                                    'plugin_cm_product_avail'       => 'Product Availability Custom Field',
                                    'plugin_cm_product_brand'       => 'Product Brand Custom Field',
                                    'plugin_cm_product_color'       => 'Product Color Custom Field',
                                    'plugin_cm_product_condition'   => 'Product Condition Custom Field',
                                    'plugin_cm_product_currency'    => 'Product Currency Custom Field',
                                    'plugin_cm_product_material'    => 'Product Material Custom Field',
                                    'plugin_cm_product_price'       => 'Product Price Custom Field',
                                    'plugin_cm_product_size'        => 'Product Size Custom Field',
                                    'plugin_cm_sameas_urls'         => 'SameAs Webpage URLs Custom Field',
				),
			),
        'head' => array(
                'limit_min' => array(
                    'og_desc_len' => 156,
                    'og_img_width' => 200,			// https://developers.facebook.com/docs/sharing/best-practices
                    'og_img_height' => 200,
                    'schema_img_width' => 400,		// https://developers.google.com/+/web/snippet/article-rendering
                    'schema_img_height' => 160,
                    'schema_article_img_width' => 696,	// https://developers.google.com/search/docs/data-types/articles
                    'schema_article_img_height' => 279,	// based on the max image ratio
                ),
                'limit_max' => array(
                    'og_img_ratio' => 3,
                    'schema_img_ratio' => 2.5,		// https://developers.google.com/+/web/snippet/article-rendering
                    'schema_article_img_ratio' => 2.5,
                ),
                'og_type_ns' => array(		// http://ogp.me/#types
                        'article' => 'http://ogp.me/ns/article#',
                        'website' => 'http://ogp.me/ns/website#',
                        'book' => 'http://ogp.me/ns/book#',
                        'books.author' => 'http://ogp.me/ns/books#',
                        'books.book' => 'http://ogp.me/ns/books#',
                        'business.business' => 'http://ogp.me/ns/business#',
                        'fitness.course' => 'http://ogp.me/ns/fitness#',
                        'game.achievement' => 'http://ogp.me/ns/game#',
                        'music.album' => 'http://ogp.me/ns/music#',
                        'music.playlist' => 'http://ogp.me/ns/music#',
                        'music.radio_station' => 'http://ogp.me/ns/music#',
                        'music.song' => 'http://ogp.me/ns/music#',
                        'place' => 'http://ogp.me/ns/place#',		
                        'product' => 'http://ogp.me/ns/product#',	
                        'product.group' => 'http://ogp.me/ns/product#',	
                        'product.item' => 'http://ogp.me/ns/product#',	
                        'profile' => 'http://ogp.me/ns/profile#',
                        'restaurant.restaurant' => 'http://ogp.me/ns/restaurant#',
                        'restaurant.menu' => 'http://ogp.me/ns/restaurant#',
                        'restaurant.menu_item' => 'http://ogp.me/ns/restaurant#',
                        'restaurant.menu_section' => 'http://ogp.me/ns/restaurant#',
                        'video.episode' => 'http://ogp.me/ns/video#',
                        'video.movie' => 'http://ogp.me/ns/video#',
                        'video.other' => 'http://ogp.me/ns/video#',
                        'video.tv_show' => 'http://ogp.me/ns/video#',
                ),
                // https://developers.facebook.com/docs/reference/opengraph/
                'og_type_mt' => array(
                        'book' => array(
                            'book:author' => '',
                            'book:isbn' => '',
                            'book:release_date' => '',
                            'book:tag' => '',
                            
                        ),
                        'books.author' => array(
                            'books:gender' => '',
                            'books:genre' => '',
                            'books:official_site' => ''
                        ),
                        'books.book' => array(
                            'books:author' => '',
                            'books:genre' => '',
                            'books:isbn' => '',
                            'books:language:locale' => '',
                            'books:page_count' => '',
                            'rating:value' => '',
                            'rating:scale' => '',
                            'books:initial_release_date' => '',
                            'books:sample' => ''
                        ),
                        'business.business' => array(
                            'business:contact_data:street_address' => 'textarea',
                            'business:contact_data:locality' => '',
                            'business:contact_data:region' => '',
                            'business:contact_data:postal_code' => '',
                            'business:contact_data:country_name' => '',
                            'business:contact_data:email' => '',
                            'business:contact_data:phone_number' => '',
                            'business:contact_data:fax_number' => '',
                            'business:contact_data:website' => '',
                            'business:hours:day' => 'textarea',
                            'business:hours:start' => 'textarea',
                            'business:hours:end' => 'textarea',
                        ),
                        'fitness.course' => array(
                            'fitness:calories' => '',
                            'fitness:custom_unit_energy:value' => '',
                            'fitness:custom_unit_energy:units' => '',
                            'fitness:distance:value' => '',
                            'fitness:distance:units' => '',
                            'fitness:duration:value' => '',
                            'fitness:duration:units' => '',
                            'fitness:live_text' => '',
                            'fitness:pace:value' => '',
                            'fitness:pace:units' => '',
                            'fitness:speed:value' => '',
                            'fitness:speed:units' => '',
                        ),
                        'game.achievement' => array(
                            'game:points' => ''
                        ),
                        'music.album' => array(
                                'music:musician' => '',
                                'music:release_date' => '',
                                'music:release_type' => '',
                                'music:song:url' => 'textarea',
                                'music:song:disc' => '',
                                'music:song:track' => '',
                        ),
                        'music.playlist' => array(
                                'music:creator' => '',
                                'music:song:url' => 'textarea',
                                'music:song:track' => '',
                                'music:song_count' => '',
                        ),
                        'music.radio_station' => array(
                                'music:creator' => '',
                        ),
                        'music.song' => array(
                                'music:album:url' => '',
                                'music:album:disc' => '',
                                'music:album:track' => '',
                                'music:duration' => '',
                                'music:musician' => '',
                        ),
                        'place' => array(
                                'place:location:latitude' => '',
                                'place:location:longitude' => '',
                                'place:location:altitude' => '',
                                'place:street_address' => 'textarea',
                                'place:locality' => '',
                                'place:region' => '',
                                'place:postal_code' => '',
                                'place:country_name' => '',
                        ),
                        'product' => array(
                                'product:price:amount' => '',
                                'product:price:currency' => '',
                        ),
                        'product.group' => array(
                            'product:retailer_group_id' => ''
                        ),
                        'product.item' => array(
                            'product:availability' => '',
                            'product:brand' => '',
                            'product:category' => '',
                            'product:color' => '',
                            'product:condition' => '',
                            'product:material' => '',
                            'product:retailer_item_id' => '',
                            'product:price:amount' => '',
                            'product:price:currency' => '',
                            'product:sale_price:amount' => '',
                            'product:sale_price:currency' => '',
                            'product:sale_price_dates:start' => '',
                            'product:sale_price_dates:end' => '',
                            'product:size' => '',
                            'product:weight:value' => '',
                            'product:weight:units' => '',
                        ),
                        'profile' => array(
                                'profile:first_name' => '',
                                'profile:last_name' => '',
                                'profile:username' => '',
                                'profile:gender' => '',
                        ),
                        'restaurant.menu' => array(
                            'restaurant:restaurant' => '',
                            'restaurant:section' => 'textarea'
                        ),
                        'restaurant.menu_item' => array(
                            'restaurant:section' => '',
                            'restaurant:variation:name' => 'textarea',
                            'restaurant:variation:price:amount' => 'textarea',
                            'restaurant:variation:price:currency' => '',
                        ),
                        'restaurant.menu_section' => array(
                            'restaurant:menu' => '',
                            'restaurant:item' => 'textarea'
                        ),
                        'restaurant.restaurant' => array(
                            'restaurant:menu' => '',
                            'restaurant:contact_info:street_address' => 'textarea',
                            'restaurant:contact_info:locality' => '',
                            'restaurant:contact_info:region' => '',
                            'restaurant:contact_info:postal_code' => '',
                            'restaurant:contact_info:country_name' => '',
                            'restaurant:contact_info:email' => '',
                            'restaurant:contact_info:phone_number' => '',
                            'restaurant:contact_info:fax_number' => '',
                            'restaurant:contact_info:website' => '',
                            'place:location:latitude' => '',
                            'place:location:longitude' => '',
                        ),
                        'video.episode' => array(
                                'video:actor:id' => 'textarea',
                                'video:actor:role' => 'textarea',
                                'video:director' => 'textarea',
                                'video:writer' => '',
                                'video:duration' => '',
                                'video:release_date' => '',
                                'video:tag' => 'textarea',
                                'video:writer' => 'textarea',
                                'video:series' => '',
                        ),
                        'video.movie' => array(
                                'video:actor:id' => 'textarea',
                                'video:actor:role' => 'textarea',
                                'video:director' => 'textarea',
                                'video:writer' => 'textarea',
                                'video:duration' => '',
                                'video:release_date' => '',
                                'video:tag' => 'textarea',
                        ),
                        'video.other' => array(
                                'video:actor:id' => 'textarea',
                                'video:actor:role' => 'textarea',
                                'video:director' => 'textarea',
                                'video:writer' => 'textarea',
                                'video:duration' => '',
                                'video:release_date' => '',
                                'video:tag' => 'textarea',
                        ),
                        'video.tv_show' => array(
                                'video:actor:id' => 'textarea',
                                'video:actor:role' => 'textarea',
                                'video:director' => 'textarea',
                                'video:writer' => 'textarea',
                                'video:duration' => '',
                                'video:release_date' => '',
                                'video:tag' => 'textarea',
                        ),
                ),
                'og_content_map' => array(
                        'product:availability' => array(	// 'instock', 'oos', or 'pending'
                            'Discontinued' => 'oos',
                            'InStock' => 'instock',
                            'InStoreOnly' => 'instock',
                            'LimitedAvailability' => 'instock',
                            'OnlineOnly' => 'instock',
                            'OutOfStock' => 'oos',
                            'PreOrder' => 'pending',
                            'SoldOut ' => 'oos',
                        ),
                        'product:condition' => array(		// 'new', 'refurbished', or 'used'
                            'DamagedCondition' => 'used',
                            'NewCondition' => 'new',
                            'RefurbishedCondition' => 'refurbished',
                            'UsedCondition' => 'used',
                        ),
                        'books:gender' => array(
                            'Male' => 'male',
                            'Female' => 'female'
                        ),
                        'business:hours:days' => array(
                            'Monday'    => 'monday',
                            'Tuesday'   => 'tuesday',
                            'Wednesday' => 'wednesday',
                            'Thursday'  => 'thursday',
                            'Friday'    => 'friday',
                            'Saturday'  => 'saturday',
                            'Sunday'    => 'sunday'
                        ),
                        'fitness:distance:units' => array(
                            'Km/s' => 'km/s',
                            'M/s' => 'm/s'
                        ),
                        'music:release_type' => array(
                            'Original Release' => 'original_release',
                            'Re Release' => 're_release',
                            'Anthology' => 'anthology'
                        ),
                        'profile:gender' => array(
                            'Male' => 'male',
                            'Female' => 'female'
                        ),
                ),
                /*
                 * WpssoSchema::get_schema_types_array() flattens the array, so AVOID DUPLICATE KEY NAMES.
                 *
                 * https URLs are preferred - for more info, see https://schema.org/docs/faq.html#19:
                 *
                 * Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup?
                 * A: There is a general trend towards using 'https' more widely, and you can
                 *    already write 'https://schema.org' in your structured data. Over time we will
                 *    migrate the schema.org site itself towards using https: as the default
                 *    version of the site and our preferred form in examples.
                 */
                'schema_type' => array(
                        'thing' => array(	// most generic type
                                'creative.work' => array(	// creative work, including books, movies, photographs, software programs, etc
                                        'article' => array(
                                                'article' => 'https://schema.org/Article',
                                                'article.news' => 'https://schema.org/NewsArticle',
                                                'article.tech' => 'https://schema.org/TechArticle',
                                                'article.scholarly' => 'https://schema.org/ScholarlyArticle',
                                                'blog.posting' => 'https://schema.org/BlogPosting',
                                                'report' => 'https://schema.org/Report',
                                                'social.media.posting' => 'https://schema.org/SocialMediaPosting',
                                        ),
                                        'book' => 'https://schema.org/Book',
                                        'blog' => 'https://schema.org/Blog',
                                        'creative.work' => 'https://schema.org/CreativeWork',
                                        'game' => 'https://schema.org/Game',
                                        'movie' => 'https://schema.org/Movie',
                                        'painting' => 'https://schema.org/Painting',
                                        'photograph' => 'https://schema.org/Photograph',
                                        'question' => 'https://schema.org/Question',
                                        'recipe' => 'https://schema.org/Recipe',
                                        'review' => array(
                                                'review' => 'https://schema.org/Review',
                                                'review.claim' => 'https://schema.org/ClaimReview',
                                        ),
                                        'sculpture' => 'https://schema.org/Sculpture',
                                        'software.application' => 'https://schema.org/SoftwareApplication',
                                        'visual.artwork' => 'https://schema.org/VisualArtwork',
                                        'webpage' => array(
                                                'webpage' => 'https://schema.org/WebPage',
                                                'webpage.about' => 'https://schema.org/AboutPage',
                                                'webpage.checkout' => 'https://schema.org/CheckoutPage',
                                                'webpage.collection' => 'https://schema.org/CollectionPage',
                                                'webpage.contact' => 'https://schema.org/ContactPage',
                                                'webpage.item' => 'https://schema.org/ItemPage',
                                                'webpage.profile' => 'https://schema.org/ProfilePage',
                                                'webpage.qa' => 'https://schema.org/QAPage',
                                                'webpage.search.results' => 'https://schema.org/SearchResultsPage',
                                        ),
                                        'website' => 'https://schema.org/WebSite',
                                ),
                                'event' => array(
                                        'event' => 'https://schema.org/Event',
                                        'event.business' => 'https://schema.org/BusinessEvent',
                                        'event.childrens' => 'https://schema.org/ChildrensEvent',
                                        'event.comedy' => 'https://schema.org/ComedyEvent',
                                        'event.dance' => 'https://schema.org/DanceEvent',
                                        'event.delivery' => 'https://schema.org/DeliveryEvent',
                                        'event.education' => 'https://schema.org/EducationEvent',
                                        'event.exhibition' => 'https://schema.org/ExhibitionEvent',
                                        'event.festival' => 'https://schema.org/Festival',
                                        'event.food' => 'https://schema.org/FoodEvent',
                                        'event.literary' => 'https://schema.org/LiteraryEvent',
                                        'event.music' => 'https://schema.org/MusicEvent',
                                        'event.publication' => 'https://schema.org/PublicationEvent',
                                        'event.sale' => 'https://schema.org/SaleEvent',
                                        'event.screening' => 'https://schema.org/ScreeningEvent',
                                        'event.social' => 'https://schema.org/SocialEvent',
                                        'event.sports' => 'https://schema.org/SportsEvent',
                                        'event.theater' => 'https://schema.org/TheaterEvent',
                                        'event.visual.arts' => 'https://schema.org/VisualArtsEvent',
                                ),
                                'intangible' => array(
                                        'alignment.object' => 'https://schema.org/AlignmentObject',
                                        'audience' => 'https://schema.org/Audience',
                                        'bed.details' => 'https://schema.org/BedDetails',
                                        'brand' => 'https://schema.org/Brand',
                                        'broadcast.channel' => 'https://schema.org/BroadcastChannel',
                                        'bus.trip' => 'https://schema.org/BusTrip',
                                        'computer.language' => 'https://schema.org/ComputerLanguage',
                                        'data.feed.item' => 'https://schema.org/DataFeedItem',
                                        'demand' => 'https://schema.org/Demand',
                                        'digital.document.permission' => 'https://schema.org/DigitalDocumentPermission',
                                        'entry.point' => 'https://schema.org/EntryPoint',
                                        'enumeration' => array(
                                                'action.status.type' => 'https://schema.org/ActionStatusType',
                                                'boarding.policy.type' => 'https://schema.org/BoardingPolicyType',
                                                'book.format.type' => 'https://schema.org/BookFormatType',
                                                'business.entity.type' => 'https://schema.org/BusinessEntityType',
                                                'business.function' => 'https://schema.org/BusinessFunction',
                                                'contact.point.option' => 'https://schema.org/ContactPointOption',
                                                'day.of.week' => 'https://schema.org/DayOfWeek',
                                                'delivery.method' => 'https://schema.org/DeliveryMethod',
                                                'digital.document.permission.type' => 'https://schema.org/DigitalDocumentPermissionType',
                                                'enumeration' => 'https://schema.org/Enumeration',
                                                'event.status.type' => 'https://schema.org/EventStatusType',
                                                'game.play.mode' => 'https://schema.org/GamePlayMode',
                                                'game.server.status' => 'https://schema.org/GameServerStatus',
                                                'gender.type' => 'https://schema.org/GenderType',
                                                'item.availability' => 'https://schema.org/ItemAvailability',
                                                'item.list.order.type' => 'https://schema.org/ItemListOrderType',
                                                'map.category.type' => 'https://schema.org/MapCategoryType',
                                                'music.album.production.type' => 'https://schema.org/MusicAlbumProductionType',
                                                'music.album.release.type' => 'https://schema.org/MusicAlbumReleaseType',
                                                'music.release.format.type' => 'https://schema.org/MusicReleaseFormatType',
                                                'offer.item.condition' => 'https://schema.org/OfferItemCondition',
                                                'order.status' => 'https://schema.org/OrderStatus',
                                                'payment.method' => 'https://schema.org/PaymentMethod',
                                                'payment.status.type' => 'https://schema.org/PaymentStatusType',
                                                'qualitative.value' => 'https://schema.org/QualitativeValue',
                                                'reservation.status.type' => 'https://schema.org/ReservationStatusType',
                                                'restricted.diet' => 'https://schema.org/RestrictedDiet',
                                                'rsvp.response.type' => 'https://schema.org/RsvpResponseType',
                                                'specialty' => array(
                                                        'medical.specialty' => array( 
                                                                'anesthesia' => 'https://health-lifesci.schema.org/Anesthesia',
                                                                'cardiovascular' => 'https://health-lifesci.schema.org/Cardiovascular',
                                                                'community.health' => 'https://health-lifesci.schema.org/CommunityHealth',
                                                                'dentistry' => 'https://health-lifesci.schema.org/Dentistry',
                                                                'dermatologic' => 'https://health-lifesci.schema.org/Dermatologic',
                                                                'dermatology' => 'https://health-lifesci.schema.org/Dermatology',
                                                                'diet.nutrition' => 'https://health-lifesci.schema.org/DietNutrition',
                                                                'emergency' => 'https://health-lifesci.schema.org/Emergency',
                                                                'endocrine' => 'https://health-lifesci.schema.org/Endocrine',
                                                                'gastroenterologic' => 'https://health-lifesci.schema.org/Gastroenterologic',
                                                                'genetic' => 'https://health-lifesci.schema.org/Genetic',
                                                                'geriatric' => 'https://health-lifesci.schema.org/Geriatric',
                                                                'gynecologic' => 'https://health-lifesci.schema.org/Gynecologic',
                                                                'hematologic' => 'https://health-lifesci.schema.org/Hematologic',
                                                                'infectious' => 'https://health-lifesci.schema.org/Infectious',
                                                                'laboratory.science' => 'https://health-lifesci.schema.org/LaboratoryScience',
                                                                'medical.specialty' => 'https://health-lifesci.schema.org/MedicalSpecialty',
                                                                'midwifery' => 'https://health-lifesci.schema.org/Midwifery',
                                                                'musculoskeletal' => 'https://health-lifesci.schema.org/Musculoskeletal',
                                                                'neurologic' => 'https://health-lifesci.schema.org/Neurologic',
                                                                'nursing' => 'https://health-lifesci.schema.org/Nursing',
                                                                'obstetric' => 'https://health-lifesci.schema.org/Obstetric',
                                                                'occupational.therapy' => 'https://health-lifesci.schema.org/OccupationalTherapy',
                                                                'oncologic' => 'https://health-lifesci.schema.org/Oncologic',
                                                                'optometric' => 'https://health-lifesci.schema.org/Optometric',
                                                                'otolaryngologic' => 'https://health-lifesci.schema.org/Otolaryngologic',
                                                                'pathology' => 'https://health-lifesci.schema.org/Pathology',
                                                                'pediatric' => 'https://health-lifesci.schema.org/Pediatric',
                                                                'pharmacy.specialty' => 'https://health-lifesci.schema.org/PharmacySpecialty',
                                                                'physiotherapy' => 'https://health-lifesci.schema.org/Physiotherapy',
                                                                'plastic.surgery' => 'https://health-lifesci.schema.org/PlasticSurgery',
                                                                'podiatric' => 'https://health-lifesci.schema.org/Podiatric',
                                                                'primary.care' => 'https://health-lifesci.schema.org/PrimaryCare',
                                                                'psychiatric' => 'https://health-lifesci.schema.org/Psychiatric',
                                                                'public.health' => 'https://health-lifesci.schema.org/PublicHealth',
                                                                'pulmonary' => 'https://health-lifesci.schema.org/Pulmonary',
                                                                'radiography' => 'https://health-lifesci.schema.org/Radiography',
                                                                'renal' => 'https://health-lifesci.schema.org/Renal',
                                                                'respiratory.therapy' => 'https://health-lifesci.schema.org/RespiratoryTherapy',
                                                                'rheumatologic' => 'https://health-lifesci.schema.org/Rheumatologic',
                                                                'speech.pathology' => 'https://health-lifesci.schema.org/SpeechPathology',
                                                                'surgical' => 'https://health-lifesci.schema.org/Surgical',
                                                                'toxicologic' => 'https://health-lifesci.schema.org/Toxicologic',
                                                                'urologic' => 'https://health-lifesci.schema.org/Urologic',
                                                        ),
                                                        'specialty' => 'https://schema.org/Specialty',
                                                ),
                                                'warranty.scope' => 'https://schema.org/WarrantyScope',
                                        ),
                                        'flight' => 'https://schema.org/Flight',
                                        'game.server' => 'https://schema.org/GameServer',
                                        'intangible' => 'https://schema.org/Intangible',
                                        'invoice' => 'https://schema.org/Invoice',
                                        'item.list' => 'https://schema.org/ItemList',
                                        'job.posting' => 'https://schema.org/JobPosting',
                                        'language' => 'https://schema.org/Language',
                                        'list.item' => 'https://schema.org/ListItem',
                                        'medical.enumeration' => array(
                                                'medical.enumeration' => 'https://health-lifesci.schema.org/MedicalEnumeration',
                                        ),
                                        'menu.item' => 'https://schema.org/MenuItem',
                                        'offer' => 'https://schema.org/Offer',
                                        'order' => 'https://schema.org/Order',
                                        'order.item' => 'https://schema.org/OrderItem',
                                        'parcel.delivery' => 'https://schema.org/ParcelDelivery',
                                        'permit' => 'https://schema.org/Permit',
                                        'program.membership' => 'https://schema.org/ProgramMembership',
                                        'property.value.specification' => 'https://schema.org/PropertyValueSpecification',
                                        'quantity' => 'https://schema.org/Quantity',
                                        'rating' => 'https://schema.org/Rating',
                                        'reservation' => 'https://schema.org/Reservation',
                                        'role' => 'https://schema.org/Role',
                                        'seat' => 'https://schema.org/Seat',
                                        'service' => 'https://schema.org/Service',
                                        'service.channel' => 'https://schema.org/ServiceChannel',
                                        'structured.value' => 'https://schema.org/StructuredValue',
                                        'ticket' => 'https://schema.org/Ticket',
                                        'train.trip' => 'https://schema.org/TrainTrip',
                                ),
                                'thing' => 'https://schema.org/Thing',
                                'organization' => array(
                                        'airline' => 'https://schema.org/Airline',
                                        'corporation' => 'https://schema.org/Corporation',
                                        'educational.organization' => array(
                                                'college.or.university' => 'https://schema.org/CollegeOrUniversity',
                                                'educational.organization' => 'https://schema.org/EducationalOrganization',
                                                'elementary.school' => 'https://schema.org/ElementarySchool',
                                                'high.school' => 'https://schema.org/HighSchool',
                                                'middle.school' => 'https://schema.org/MiddleSchool',
                                                'preschool' => 'https://schema.org/Preschool',
                                                'school' => 'https://schema.org/School',
                                        ),
                                        'government.organization' => 'https://schema.org/GovernmentOrganization',
                                        'medical.organization' => array(
                                                'medical.organization' => 'https://schema.org/MedicalOrganization',
                                                'pharmacy' => 'https://schema.org/Pharmacy',
                                                'physician' => 'https://schema.org/Physician',
                                        ),
                                        'non-governmental.organization' => 'https://schema.org/NGO',
                                        'organization' => 'https://schema.org/Organization',
                                        'performing.group' => array(
                                                'dance.group' => 'https://schema.org/DanceGroup',
                                                'music.group' => 'https://schema.org/MusicGroup',
                                                'performing.group' => 'https://schema.org/PerformingGroup',
                                                'theater.group' => 'https://schema.org/TheaterGroup',
                                        ),
                                        'sports.organization' => array(
                                                'sports.team' => 'https://schema.org/SportsTeam',
                                                'sports.organization' => 'https://schema.org/SportsOrganization',
                                        ),
                                ),
                                'person' => 'https://schema.org/Person',
                                'place' => array(
                                        'administrative.area' => 'https://schema.org/AdministrativeArea',
                                        'civic.structure' => array(
                                                'airport' => 'https://schema.org/Airport',
                                                'aquarium' => 'https://schema.org/Aquarium',
                                                'beach' => 'https://schema.org/Beach',
                                                'bridge' => 'https://schema.org/Bridge',
                                                'bus.station' => 'https://schema.org/BusStation',
                                                'bus.stop' => 'https://schema.org/BusStop',
                                                'cemetary' => 'https://schema.org/Cemetery',
                                                'civic.structure' => 'https://schema.org/CivicStructure',
                                                'crematorium' => 'https://schema.org/Crematorium',
                                                'event.venu' => 'https://schema.org/EventVenue',
                                                'government.building' => 'https://schema.org/GovernmentBuilding',
                                                'museum' => 'https://schema.org/Museum',
                                                'music.venu' => 'https://schema.org/MusicVenue',
                                                'park' => 'https://schema.org/Park',
                                                'parking.facility' => 'https://schema.org/ParkingFacility',
                                                'performing.arts.theatre' => 'https://schema.org/PerformingArtsTheater',
                                                'place.of.worship' => 'https://schema.org/PlaceOfWorship',
                                                'playground' => 'https://schema.org/Playground',
                                                'rv.park' => 'https://schema.org/RVPark',
                                                'subway.station' => 'https://schema.org/SubwayStation',
                                                'taxi.stand' => 'https://schema.org/TaxiStand',
                                                'train.station' => 'https://schema.org/TrainStation',
                                                'zoo' => 'https://schema.org/Zoo',
                                        ),
                                        'landform' => 'https://schema.org/Landform',
                                        'landmarks.or.historical.buildings' => 'https://schema.org/LandmarksOrHistoricalBuildings',
                                        'local.business' => array(
                                                'animal.shelter' => 'https://schema.org/AnimalShelter',
                                                'automotive.business' => array(
                                                        'auto.body.shop' => 'https://schema.org/AutoBodyShop',
                                                        'auto.dealer' => 'https://schema.org/AutoDealer',
                                                        'auto.parts.store' => 'https://schema.org/AutoPartsStore',
                                                        'auto.rental' => 'https://schema.org/AutoRental',
                                                        'auto.repair' => 'https://schema.org/AutoRepair',
                                                        'auto.wash' => 'https://schema.org/AutoWash',
                                                        'automotive.business' => 'https://schema.org/AutomotiveBusiness',
                                                        'gas.station' => 'https://schema.org/GasStation',
                                                        'motorcycle.dealer' => 'https://schema.org/MotorcycleDealer',
                                                        'motorcycle.repair' => 'https://schema.org/MotorcycleRepair ',
                                                ),
                                                'child.care' => 'https://schema.org/ChildCare',
                                                'dentist' => 'https://schema.org/Dentist',
                                                'dry.cleaning.or.laundry' => 'https://schema.org/DryCleaningOrLaundry',
                                                'emergency.service' => array(
                                                        'emergency.service' => 'https://schema.org/EmergencyService',
                                                        'fire.station' => 'https://schema.org/FireStation',
                                                        'hospital' => 'https://schema.org/Hospital',
                                                        'police.station' => 'https://schema.org/PoliceStation',
                                                ),
                                                'employement.agency' => 'https://schema.org/EmploymentAgency',
                                                'entertainment.business' => array(
                                                        'entertainment.business' => 'https://schema.org/EntertainmentBusiness',
                                                        'movie.theatre' => 'https://schema.org/MovieTheatre',
                                                ),
                                                'financial.service' => 'https://schema.org/FinancialService',
                                                'food.establishment' => array(
                                                        'bakery' => 'https://schema.org/Bakery',
                                                        'bar.or.pub' => 'https://schema.org/BarOrPub',
                                                        'brewery' => 'https://schema.org/Brewery',
                                                        'cafe.or.coffee.shop' => 'https://schema.org/CafeOrCoffeeShop',
                                                        'fast.food.restaurant' => 'https://schema.org/FastFoodRestaurant',
                                                        'food.establishment' => 'https://schema.org/FoodEstablishment',
                                                        'ice.cream.shop' => 'https://schema.org/IceCreamShop',
                                                        'restaurant' => 'https://schema.org/Restaurant',
                                                        'winery' => 'https://schema.org/Winery',
                                                ),
                                                'government.office' => 'https://schema.org/GovernmentOffice',
                                                'health.and.beauty.business' => 'https://schema.org/HealthAndBeautyBusiness',
                                                'home.and.construction.business' => array(
                                                        'electrician' => 'https://schema.org/Electrician',
                                                        'general.contractor' => 'https://schema.org/GeneralContractor',
                                                        'hvac.business' => 'https://schema.org/HVACBusiness',
                                                        'home.and.construction.business' => 'https://schema.org/HomeAndConstructionBusiness',
                                                        'house.painter' => 'https://schema.org/HousePainter',
                                                        'locksmith' => 'https://schema.org/Locksmith',
                                                        'moving.company' => 'https://schema.org/MovingCompany',
                                                        'plumber' => 'https://schema.org/Plumber',
                                                        'roofing.contractor' => 'https://schema.org/RoofingContractor',
                                                ),
                                                'internet.cafe' => 'https://schema.org/InternetCafe',
                                                'legal.service' => array(
                                                        'attorney' => 'https://schema.org/Attorney',
                                                        'legal.service' => 'https://schema.org/LegalService',
                                                        'notary' => 'https://schema.org/Notary',
                                                ),
                                                'library' => 'https://schema.org/Library',
                                                'local.business' => 'https://schema.org/LocalBusiness',
                                                'lodging.business' => array(
                                                        'campground' => 'https://schema.org/Campground',
                                                        'lodging.business' => 'https://schema.org/LodgingBusiness',
                                                ),
                                                'medical.business' => array(
                                                        'community.health.business' => 'https://health-lifesci.schema.org/CommunityHealth',
                                                        'dentist.business' => 'https://health-lifesci.schema.org/Dentist',
                                                        'dermatology.business' => 'https://health-lifesci.schema.org/Dermatology',
                                                        'diet.nutrition.business' => 'https://health-lifesci.schema.org/DietNutrition',
                                                        'emergency.business' => 'https://health-lifesci.schema.org/Emergency',
                                                        'geriatric.business' => 'https://health-lifesci.schema.org/Geriatric',
                                                        'gynecologic.business' => 'https://health-lifesci.schema.org/Gynecologic',
                                                        'medical.business' => 'https://health-lifesci.schema.org/MedicalBusiness',
                                                        'medical.clinic.business' => 'https://health-lifesci.schema.org/MedicalClinic',
                                                        'midwifery.business' => 'https://health-lifesci.schema.org/Midwifery',
                                                        'nursing.business' => 'https://health-lifesci.schema.org/Nursing',
                                                        'obstetric.business' => 'https://health-lifesci.schema.org/Obstetric',
                                                        'oncologic.business' => 'https://health-lifesci.schema.org/Oncologic',
                                                        'optician.business' => 'https://health-lifesci.schema.org/Optician',
                                                        'optometric.business' => 'https://health-lifesci.schema.org/Optometric',
                                                        'otolaryngologic.business' => 'https://health-lifesci.schema.org/Otolaryngologic',
                                                        'pediatric.business' => 'https://health-lifesci.schema.org/Pediatric',
                                                        'pharmacy.business' => 'https://health-lifesci.schema.org/Pharmacy',
                                                        'physician.business' => 'https://health-lifesci.schema.org/Physician',
                                                        'physiotherapy.business' => 'https://health-lifesci.schema.org/Physiotherapy',
                                                        'plasticSurgery.business' => 'https://health-lifesci.schema.org/PlasticSurgery',
                                                        'podiatric.business' => 'https://health-lifesci.schema.org/Podiatric',
                                                        'primaryCare.business' => 'https://health-lifesci.schema.org/PrimaryCare',
                                                        'psychiatric.business' => 'https://health-lifesci.schema.org/Psychiatric',
                                                        'publicHealth.business' => 'https://health-lifesci.schema.org/PublicHealth',
                                                ),
                                                'professional.service' => 'https://schema.org/ProfessionalService',
                                                'radio.station' => 'https://schema.org/RadioStation',
                                                'real.estate.agent' => 'https://schema.org/RealEstateAgent',
                                                'recycling.center' => 'https://schema.org/RecyclingCenter',
                                                'self.storage' => 'https://schema.org/SelfStorage',
                                                'shopping.center' => 'https://schema.org/ShoppingCenter',
                                                'sports.activity.location' => array(
                                                        'sports.activity.location' => 'https://schema.org/SportsActivityLocation',
                                                        'stadium.or.arena' => 'https://schema.org/StadiumOrArena',
                                                ),
                                                'store' => array(
                                                        'bike.store' => 'https://schema.org/BikeStore',
                                                        'book.store' => 'https://schema.org/BookStore',
                                                        'clothing.store' => 'https://schema.org/ClothingStore',
                                                        'computer.store' => 'https://schema.org/ComputerStore',
                                                        'convenience.store' => 'https://schema.org/ConvenienceStore',
                                                        'department.store' => 'https://schema.org/DepartmentStore',
                                                        'electronics.store' => 'https://schema.org/ElectronicsStore',
                                                        'florist' => 'https://schema.org/Florist',
                                                        'flower.shop' => 'https://schema.org/Florist',
                                                        'furniture.store' => 'https://schema.org/FurnitureStore',
                                                        'garden.store' => 'https://schema.org/GardenStore',
                                                        'grocery.store' => 'https://schema.org/GroceryStore',
                                                        'hardware.store' => 'https://schema.org/HardwareStore',
                                                        'hobby.shop' => 'https://schema.org/HobbyShop',
                                                        'home.goods.store' => 'https://schema.org/HomeGoodsStore',
                                                        'jewelry.store' => 'https://schema.org/JewelryStore',
                                                        'liquor.store' => 'https://schema.org/LiquorStore',
                                                        'mens.clothing.store' => 'https://schema.org/MensClothingStore',
                                                        'mobile.phone.store' => 'https://schema.org/MobilePhoneStore',
                                                        'movie.rental.store' => 'https://schema.org/MovieRentalStore',
                                                        'music.store' => 'https://schema.org/MusicStore',
                                                        'office.equipment.store' => 'https://schema.org/OfficeEquipmentStore',
                                                        'outlet.store' => 'https://schema.org/OutletStore',
                                                        'pawn.shop' => 'https://schema.org/PawnShop',
                                                        'pet.store' => 'https://schema.org/PetStore',
                                                        'shoe.store' => 'https://schema.org/ShoeStore',
                                                        'sporting.goods.store' => 'https://schema.org/SportingGoodsStore',
                                                        'store' => 'https://schema.org/Store',
                                                        'tire.shop' => 'https://schema.org/TireShop',
                                                        'toy.store' => 'https://schema.org/ToyStore',
                                                        'wholesale.store' => 'https://schema.org/WholesaleStore',
                                                ),
                                                'television.station' => 'https://schema.org/TelevisionStation',
                                                'tourist.information.center' => 'https://schema.org/TouristInformationCenter',
                                                'travel.agency' => 'https://schema.org/TravelAgency',
                                        ),
                                        'place' => 'https://schema.org/Place',
                                        'residence' => 'https://schema.org/Residence',
                                        'tourist.attraction' => 'https://schema.org/TouristAttraction',
                                ),
                                'product' => array(
                                        'individual.product' => 'https://schema.org/IndividualProduct',	// individual product w unique serial number
                                        'product' => 'https://schema.org/Product',
                                        'product.model' => 'https://schema.org/ProductModel',
                                        'some.products' => 'https://schema.org/SomeProducts',
                                        'vehicle' => array(
                                                'bus.or.coach' => 'https://auto.schema.org/BusOrCoach',
                                                'car' => 'https://auto.schema.org/Car',
                                                'motorcycle' => 'https://auto.schema.org/Motorcycle',
                                                'motorized.bicycle' => 'https://auto.schema.org/MotorizedBicycle',
                                                'vehicle' => 'https://auto.schema.org/Vehicle',
                                        ),
                                ),
                                'thing' => 'https://schema.org/Thing',
                        ),
                ),
        ),
);
    
}
