<?php namespace CsSeoMegaBundlePack\Controllers\AdminPageBuilder\onPageOptimization\Tabs\Meta;
/**
 * Settings
 * 
 * @package Social Analytics
 * @since 1.0.0
 * @author CodeSolz <customer-service@codesolz.net>
 */

use CsSeoMegaBundlePack\Helper;
use CsSeoMegaBundlePack\Controllers\AdminPageBuilder\onPageOptimization\Common\CommonText;
use CsSeoMegaBundlePack\Models\CommonQuery\CsQuery;
use CsSeoMegaBundlePack\Controllers\AdminPageBuilder\onPageOptimization\Tabs\Meta\includes\MetaTagsTabs;

class MetaTagLists {
    
    protected $http;
    private $options;


    public function __construct( $Http ) {
        $this->http = $Http;
        
        //init settings
        $this->init_settings();
        
    }
    
    public function load_page_builder( $common_text ){
        $TA = new MetaTagsTabs();
        
//        pre_print($this->options);
        
        $data = array_merge( CommonText::form_element( 'meta_tags_list', 'aios-metatags-settings' ), array(
           'CommonText' => $common_text,
           'page_title' =>  __( 'Meta Tags List', SR_TEXTDOMAIN ),
           'page_subtitle' =>  __( 'Let\'s you manage social meta tags', SR_TEXTDOMAIN ),
           'tabs' => $TA->meta_tagslist_tabs(),
           'tab_assets' => $TA->get_all_metas(),
           'label_submit_btn' => __( 'Save Settings', SR_TEXTDOMAIN ),
           'des_input' => __( 'Select Meta Robots for name', SR_TEXTDOMAIN ),
           'label_follow' => __( 'Follow', SR_TEXTDOMAIN ),
           'label_nofollow' => __( 'No Follow', SR_TEXTDOMAIN ),
           'options' => $this->options,
           'panel_subtitle' => __( 'Basic Setup', SR_TEXTDOMAIN ),
           'hints_title'=> sprintf( __( 'All Head Meta Tag List Generated by %s', SR_TEXTDOMAIN ), Helper::get('PLUGIN_PREFIX') ),
           'app_create_hints' => array(
               sprintf( __( '%s adds the following Google / SEO, Facebook, Open Graph, Rich Pin, Schema, and Twitter Card HTML tags to the <code> &lt;head&gt; </code> section of your webpages.' , SR_TEXTDOMAIN ), Helper::get('PLUGIN_PREFIX')),
               __( 'If your theme or another plugin already creates one or more of these HTML tags, you can check them here to prevent duplicates from being added.', SR_TEXTDOMAIN )
           ),
       ));
       add_action('admin_footer', [$this, '_addFooter_script']);
       return  view( '@CsSeoMegaBundlePack/onPageOptimization/tabs/Meta/MetaTagLists.twig', $data );
    }
    
    function _addFooter_script(){
        ?>
            <script type="text/javascript">
                ( function( $ ) {
                        $( document ).ready( function() {
                            var _obj = {
                                $: $,
                                form_reset: true
//                                redirect: window.location.href
                            };
                            var form_general_options = new Aios_Form_Handler( _obj );
                            form_general_options.setup( "#title_metas_settings" );
                           
                        } );
                } )( jQuery );
            </script>
        <?php
    }
    
    /**
     * Init settings
     */
    private function init_settings(){
        $this->options = CsQuery::Cs_Get_Option(array(
            'option_name' => 'aios_metas_stop_render',
            'json' => true,
            'json_array' => true
        ));
    }
}
